# Generated by Django 4.2.1 on 2023-06-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.topic'),
        ),
    ]
