# Generated by Django 4.2.1 on 2023-06-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='My Post', max_length=200),
        ),
    ]
